# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: tr

pipeline:
  - name: EntitySynonymMapper
  - name: WhitespaceTokenizer
    intent_tokenization_flag: True
    intent_split_symbol: "+"
  - name: CRFEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    strip_accents: "unicode"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    evaluate_on_number_of_examples: 50
    evaluate_every_number_of_epochs: 5
    tensorboard_log_directory: "./tensorboard"
    tensorboard_log_level: "epoch"



# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: TEDPolicy
    max_history: 10
    epochs: 100
    evaluate_on_number_of_examples: 50
    evaluate_every_number_of_epochs: 5
    tensorboard_log_directory: "./tensorboard"
  - name: AugmentedMemoizationPolicy
    max_history: 6
  - name: FallbackPolicy
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_action_name: 'utter_fallback'
  - name: MappingPolicy